//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Locations = new HashSet<Location>();
            this.Academics = new HashSet<Academic>();
        }
    
        public int CityID { get; set; }
        public string Name { get; set; }
        public string AccentName { get; set; }
        public string CountryCode { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public System.Data.Entity.Spatial.DbGeography Point { get; set; }
        public string Region { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<Academic> Academics { get; set; }
    }
}
