//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyServiceClient
    {
        public System.Guid CompanyServiceClientGuid { get; set; }
        public long CompanyProductAndServiceID { get; set; }
        public int UserID { get; set; }
        public int ExpectedAttendeeCount { get; set; }
        public Nullable<byte> Day { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
    
        public virtual CompanyService CompanyService { get; set; }
        public virtual UserInfoPerson UserInfoPerson { get; set; }
    }
}
