//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyUserRating
    {
        public long CompanyUserRatingID { get; set; }
        public int CompanyID { get; set; }
        public int EmployeeID { get; set; }
        public byte Rating { get; set; }
        public System.DateTime Added { get; set; }
    
        public virtual UserInfoCompany UserInfoCompany { get; set; }
        public virtual UserInfoPerson UserInfoPerson { get; set; }
    }
}
