//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDepartment
    {
        public int UserID { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<int> AssignedByUserID { get; set; }
        public System.DateTime Added { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual UserInfoCompany UserInfoCompany { get; set; }
        public virtual UserInfoCompany UserInfoCompany1 { get; set; }
    }
}
