//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyServiceEnlistedFacility
    {
        public System.Guid CompanyServiceEnlistedFacilityGuid { get; set; }
        public long CompanyProductAndServiceID { get; set; }
        public long CompanyServiceFacilityID { get; set; }
    
        public virtual CompanyProductAndService CompanyProductAndService { get; set; }
        public virtual CompanyServiceFacility CompanyServiceFacility { get; set; }
    }
}
