//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyServiceEquipment
    {
        public CompanyServiceEquipment()
        {
            this.CompanyServiceEnlistedEquipments = new HashSet<CompanyServiceEnlistedEquipment>();
        }
    
        public long ConmpanyServiceEquipmentID { get; set; }
        public int UserID { get; set; }
        public string Name { get; set; }
        public string Capacity { get; set; }
        public Nullable<decimal> Charge { get; set; }
    
        public virtual ICollection<CompanyServiceEnlistedEquipment> CompanyServiceEnlistedEquipments { get; set; }
        public virtual UserInfoCompany UserInfoCompany { get; set; }
    }
}
