//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.UserLanguages = new HashSet<UserLanguage>();
        }
    
        public int LanguageID { get; set; }
        public string Name { get; set; }
        public byte TotalRequests { get; set; }
    
        public virtual ICollection<UserLanguage> UserLanguages { get; set; }
    }
}
