//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int LocationID { get; set; }
        public int UserID { get; set; }
        public Nullable<byte> LocationType { get; set; }
        public string Street { get; set; }
        public Nullable<int> TownID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> StateID { get; set; }
        public string CountryCode { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public bool IsTemporary { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual LocationType LocationType1 { get; set; }
        public virtual Town Town { get; set; }
        public virtual LocationTemporary LocationTemporary { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
