//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageRule
    {
        public long MessageRuleId { get; set; }
        public long MessageFolderId { get; set; }
        public byte RuleUserSelection { get; set; }
        public byte RuleTypeUser { get; set; }
        public System.Guid EntryContacts { get; set; }
        public System.Guid EntryGroups { get; set; }
        public byte RuleTypeSubject { get; set; }
        public string Subject { get; set; }
        public System.DateTime Created { get; set; }
        public bool ApplyOnOldMessages { get; set; }
    
        public virtual MessageFolder MessageFolder { get; set; }
    }
}
