//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageFolder
    {
        public MessageFolder()
        {
            this.MessageRules = new HashSet<MessageRule>();
        }
    
        public long MessageFolderId { get; set; }
        public int UserId { get; set; }
        public int FolderId { get; set; }
        public string Name { get; set; }
        public System.DateTime Created { get; set; }
        public bool Mute { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<MessageRule> MessageRules { get; set; }
    }
}
