//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long NotificationID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> OriginatorID { get; set; }
        public Nullable<int> TargetGroupID { get; set; }
        public Nullable<long> EventID { get; set; }
        public string Notification1 { get; set; }
        public System.DateTime SentDate { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public Nullable<System.DateTime> ClickedDate { get; set; }
        public short NotificationTypeID { get; set; }
        public Nullable<long> TargetPostId { get; set; }
    }
}
