//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnershipType
    {
        public OwnershipType()
        {
            this.UserInfoCompanies = new HashSet<UserInfoCompany>();
        }
    
        public byte OwnershipTypeID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<UserInfoCompany> UserInfoCompanies { get; set; }
    }
}
