//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public int PositionID { get; set; }
        public string Name { get; set; }
        public byte TotalRequests { get; set; }
        public byte Weight { get; set; }
    }
}
