//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestID { get; set; }
        public int RequestedToID { get; set; }
        public int RequestedFromID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<long> EventID { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public short RequestTypeID { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<System.DateTime> ClickedDate { get; set; }
    
        public virtual RequestType RequestType { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual UserInfo UserInfo1 { get; set; }
        public virtual Event Event { get; set; }
    }
}
