//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCategory
    {
        public UserCategory()
        {
            this.UserCategoryFriends = new HashSet<UserCategoryFriend>();
        }
    
        public int UserID { get; set; }
        public int UserCategoryTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<UserCategoryFriend> UserCategoryFriends { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
