//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfoCompany
    {
        public UserInfoCompany()
        {
            this.CompanyDepartments = new HashSet<CompanyDepartment>();
            this.CompanyDepartments1 = new HashSet<CompanyDepartment>();
            this.CompanyDepartmentEmployees = new HashSet<CompanyDepartmentEmployee>();
            this.CompanyUserRatings = new HashSet<CompanyUserRating>();
            this.SettingCompanies = new HashSet<SettingCompany>();
            this.CompanyProductAndServices = new HashSet<CompanyProductAndService>();
            this.CompanyPSCategories = new HashSet<CompanyPSCategory>();
            this.CompanyPSRooms = new HashSet<CompanyPSRoom>();
            this.CompanyPSTables = new HashSet<CompanyPSTable>();
            this.CompanyServiceEquipments = new HashSet<CompanyServiceEquipment>();
            this.CompanyServiceFacilities = new HashSet<CompanyServiceFacility>();
        }
    
        public int UserID { get; set; }
        public string Name { get; set; }
        public System.DateTime Established { get; set; }
        public Nullable<byte> IndustryID { get; set; }
        public Nullable<byte> OwnershipTypeID { get; set; }
    
        public virtual ICollection<CompanyDepartment> CompanyDepartments { get; set; }
        public virtual ICollection<CompanyDepartment> CompanyDepartments1 { get; set; }
        public virtual ICollection<CompanyDepartmentEmployee> CompanyDepartmentEmployees { get; set; }
        public virtual ICollection<CompanyUserRating> CompanyUserRatings { get; set; }
        public virtual Industry Industry { get; set; }
        public virtual OwnershipType OwnershipType { get; set; }
        public virtual ICollection<SettingCompany> SettingCompanies { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<CompanyProductAndService> CompanyProductAndServices { get; set; }
        public virtual ICollection<CompanyPSCategory> CompanyPSCategories { get; set; }
        public virtual ICollection<CompanyPSRoom> CompanyPSRooms { get; set; }
        public virtual ICollection<CompanyPSTable> CompanyPSTables { get; set; }
        public virtual ICollection<CompanyServiceEquipment> CompanyServiceEquipments { get; set; }
        public virtual ICollection<CompanyServiceFacility> CompanyServiceFacilities { get; set; }
    }
}
