/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace TekTak.iLoop.Kauwa
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class CompanyTree : TBase
  {
    private int _userId;
    private bool _ignoreSisters;
    private bool _showChildCompanyOnly;

    public int UserId
    {
      get
      {
        return _userId;
      }
      set
      {
        __isset.userId = true;
        this._userId = value;
      }
    }

    public bool IgnoreSisters
    {
      get
      {
        return _ignoreSisters;
      }
      set
      {
        __isset.ignoreSisters = true;
        this._ignoreSisters = value;
      }
    }

    public bool ShowChildCompanyOnly
    {
      get
      {
        return _showChildCompanyOnly;
      }
      set
      {
        __isset.showChildCompanyOnly = true;
        this._showChildCompanyOnly = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool userId;
      public bool ignoreSisters;
      public bool showChildCompanyOnly;
    }

    public CompanyTree() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              UserId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Bool) {
              IgnoreSisters = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Bool) {
              ShowChildCompanyOnly = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("CompanyTree");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.userId) {
        field.Name = "userId";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(UserId);
        oprot.WriteFieldEnd();
      }
      if (__isset.ignoreSisters) {
        field.Name = "ignoreSisters";
        field.Type = TType.Bool;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(IgnoreSisters);
        oprot.WriteFieldEnd();
      }
      if (__isset.showChildCompanyOnly) {
        field.Name = "showChildCompanyOnly";
        field.Type = TType.Bool;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(ShowChildCompanyOnly);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("CompanyTree(");
      bool __first = true;
      if (__isset.userId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("UserId: ");
        __sb.Append(UserId);
      }
      if (__isset.ignoreSisters) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("IgnoreSisters: ");
        __sb.Append(IgnoreSisters);
      }
      if (__isset.showChildCompanyOnly) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ShowChildCompanyOnly: ");
        __sb.Append(ShowChildCompanyOnly);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
