/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace TekTak.iLoop.Kauwa
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ContactSuggestions : TBase
  {
    private long _contactCustomId;
    private int _contactId;
    private int _contactTypeId;
    private int _userId;
    private string _userName;
    private string _displayName;
    private string _picture;
    private int _fieldId;
    private string _name;
    private string _value;
    private string _originalName;
    private string _originalValue;
    private int _contactChatNetworkId;
    private long _referralContactCustomId;
    private string _added;

    public long ContactCustomId
    {
      get
      {
        return _contactCustomId;
      }
      set
      {
        __isset.contactCustomId = true;
        this._contactCustomId = value;
      }
    }

    public int ContactId
    {
      get
      {
        return _contactId;
      }
      set
      {
        __isset.contactId = true;
        this._contactId = value;
      }
    }

    public int ContactTypeId
    {
      get
      {
        return _contactTypeId;
      }
      set
      {
        __isset.contactTypeId = true;
        this._contactTypeId = value;
      }
    }

    public int UserId
    {
      get
      {
        return _userId;
      }
      set
      {
        __isset.userId = true;
        this._userId = value;
      }
    }

    public string UserName
    {
      get
      {
        return _userName;
      }
      set
      {
        __isset.userName = true;
        this._userName = value;
      }
    }

    public string DisplayName
    {
      get
      {
        return _displayName;
      }
      set
      {
        __isset.displayName = true;
        this._displayName = value;
      }
    }

    public string Picture
    {
      get
      {
        return _picture;
      }
      set
      {
        __isset.picture = true;
        this._picture = value;
      }
    }

    public int FieldId
    {
      get
      {
        return _fieldId;
      }
      set
      {
        __isset.fieldId = true;
        this._fieldId = value;
      }
    }

    public string Name
    {
      get
      {
        return _name;
      }
      set
      {
        __isset.name = true;
        this._name = value;
      }
    }

    public string Value
    {
      get
      {
        return _value;
      }
      set
      {
        __isset.@value = true;
        this._value = value;
      }
    }

    public string OriginalName
    {
      get
      {
        return _originalName;
      }
      set
      {
        __isset.originalName = true;
        this._originalName = value;
      }
    }

    public string OriginalValue
    {
      get
      {
        return _originalValue;
      }
      set
      {
        __isset.originalValue = true;
        this._originalValue = value;
      }
    }

    public int ContactChatNetworkId
    {
      get
      {
        return _contactChatNetworkId;
      }
      set
      {
        __isset.contactChatNetworkId = true;
        this._contactChatNetworkId = value;
      }
    }

    public long ReferralContactCustomId
    {
      get
      {
        return _referralContactCustomId;
      }
      set
      {
        __isset.referralContactCustomId = true;
        this._referralContactCustomId = value;
      }
    }

    public string Added
    {
      get
      {
        return _added;
      }
      set
      {
        __isset.added = true;
        this._added = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool contactCustomId;
      public bool contactId;
      public bool contactTypeId;
      public bool userId;
      public bool userName;
      public bool displayName;
      public bool picture;
      public bool fieldId;
      public bool name;
      public bool @value;
      public bool originalName;
      public bool originalValue;
      public bool contactChatNetworkId;
      public bool referralContactCustomId;
      public bool added;
    }

    public ContactSuggestions() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              ContactCustomId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              ContactId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              ContactTypeId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I32) {
              UserId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.String) {
              UserName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.String) {
              DisplayName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == TType.String) {
              Picture = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 8:
            if (field.Type == TType.I32) {
              FieldId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 9:
            if (field.Type == TType.String) {
              Name = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 10:
            if (field.Type == TType.String) {
              Value = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 11:
            if (field.Type == TType.String) {
              OriginalName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 12:
            if (field.Type == TType.String) {
              OriginalValue = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 13:
            if (field.Type == TType.I32) {
              ContactChatNetworkId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 14:
            if (field.Type == TType.I64) {
              ReferralContactCustomId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 15:
            if (field.Type == TType.String) {
              Added = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ContactSuggestions");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.contactCustomId) {
        field.Name = "contactCustomId";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(ContactCustomId);
        oprot.WriteFieldEnd();
      }
      if (__isset.contactId) {
        field.Name = "contactId";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ContactId);
        oprot.WriteFieldEnd();
      }
      if (__isset.contactTypeId) {
        field.Name = "contactTypeId";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ContactTypeId);
        oprot.WriteFieldEnd();
      }
      if (__isset.userId) {
        field.Name = "userId";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(UserId);
        oprot.WriteFieldEnd();
      }
      if (UserName != null && __isset.userName) {
        field.Name = "userName";
        field.Type = TType.String;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(UserName);
        oprot.WriteFieldEnd();
      }
      if (DisplayName != null && __isset.displayName) {
        field.Name = "displayName";
        field.Type = TType.String;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(DisplayName);
        oprot.WriteFieldEnd();
      }
      if (Picture != null && __isset.picture) {
        field.Name = "picture";
        field.Type = TType.String;
        field.ID = 7;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Picture);
        oprot.WriteFieldEnd();
      }
      if (__isset.fieldId) {
        field.Name = "fieldId";
        field.Type = TType.I32;
        field.ID = 8;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(FieldId);
        oprot.WriteFieldEnd();
      }
      if (Name != null && __isset.name) {
        field.Name = "name";
        field.Type = TType.String;
        field.ID = 9;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Name);
        oprot.WriteFieldEnd();
      }
      if (Value != null && __isset.@value) {
        field.Name = "value";
        field.Type = TType.String;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Value);
        oprot.WriteFieldEnd();
      }
      if (OriginalName != null && __isset.originalName) {
        field.Name = "originalName";
        field.Type = TType.String;
        field.ID = 11;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(OriginalName);
        oprot.WriteFieldEnd();
      }
      if (OriginalValue != null && __isset.originalValue) {
        field.Name = "originalValue";
        field.Type = TType.String;
        field.ID = 12;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(OriginalValue);
        oprot.WriteFieldEnd();
      }
      if (__isset.contactChatNetworkId) {
        field.Name = "contactChatNetworkId";
        field.Type = TType.I32;
        field.ID = 13;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ContactChatNetworkId);
        oprot.WriteFieldEnd();
      }
      if (__isset.referralContactCustomId) {
        field.Name = "referralContactCustomId";
        field.Type = TType.I64;
        field.ID = 14;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(ReferralContactCustomId);
        oprot.WriteFieldEnd();
      }
      if (Added != null && __isset.added) {
        field.Name = "added";
        field.Type = TType.String;
        field.ID = 15;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Added);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ContactSuggestions(");
      bool __first = true;
      if (__isset.contactCustomId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ContactCustomId: ");
        __sb.Append(ContactCustomId);
      }
      if (__isset.contactId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ContactId: ");
        __sb.Append(ContactId);
      }
      if (__isset.contactTypeId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ContactTypeId: ");
        __sb.Append(ContactTypeId);
      }
      if (__isset.userId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("UserId: ");
        __sb.Append(UserId);
      }
      if (UserName != null && __isset.userName) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("UserName: ");
        __sb.Append(UserName);
      }
      if (DisplayName != null && __isset.displayName) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("DisplayName: ");
        __sb.Append(DisplayName);
      }
      if (Picture != null && __isset.picture) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Picture: ");
        __sb.Append(Picture);
      }
      if (__isset.fieldId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("FieldId: ");
        __sb.Append(FieldId);
      }
      if (Name != null && __isset.name) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Name: ");
        __sb.Append(Name);
      }
      if (Value != null && __isset.@value) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Value: ");
        __sb.Append(Value);
      }
      if (OriginalName != null && __isset.originalName) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("OriginalName: ");
        __sb.Append(OriginalName);
      }
      if (OriginalValue != null && __isset.originalValue) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("OriginalValue: ");
        __sb.Append(OriginalValue);
      }
      if (__isset.contactChatNetworkId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ContactChatNetworkId: ");
        __sb.Append(ContactChatNetworkId);
      }
      if (__isset.referralContactCustomId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ReferralContactCustomId: ");
        __sb.Append(ReferralContactCustomId);
      }
      if (Added != null && __isset.added) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Added: ");
        __sb.Append(Added);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
