/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace TekTak.iLoop.Kauwa
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Employment : TBase
  {
    private int _userId;
    private short _mode;
    private CompanyEmployeeInfo _employeeInfo;
    private long _personEmploymentId;
    private long _requestId;
    private City _city;
    private DbStatus _dbStatus;
    private string _employeeIds;
    private int _rating;

    public int UserId
    {
      get
      {
        return _userId;
      }
      set
      {
        __isset.userId = true;
        this._userId = value;
      }
    }

    public short Mode
    {
      get
      {
        return _mode;
      }
      set
      {
        __isset.mode = true;
        this._mode = value;
      }
    }

    public CompanyEmployeeInfo EmployeeInfo
    {
      get
      {
        return _employeeInfo;
      }
      set
      {
        __isset.employeeInfo = true;
        this._employeeInfo = value;
      }
    }

    public long PersonEmploymentId
    {
      get
      {
        return _personEmploymentId;
      }
      set
      {
        __isset.personEmploymentId = true;
        this._personEmploymentId = value;
      }
    }

    public long RequestId
    {
      get
      {
        return _requestId;
      }
      set
      {
        __isset.requestId = true;
        this._requestId = value;
      }
    }

    public City City
    {
      get
      {
        return _city;
      }
      set
      {
        __isset.city = true;
        this._city = value;
      }
    }

    public DbStatus DbStatus
    {
      get
      {
        return _dbStatus;
      }
      set
      {
        __isset.dbStatus = true;
        this._dbStatus = value;
      }
    }

    public string EmployeeIds
    {
      get
      {
        return _employeeIds;
      }
      set
      {
        __isset.employeeIds = true;
        this._employeeIds = value;
      }
    }

    public int Rating
    {
      get
      {
        return _rating;
      }
      set
      {
        __isset.rating = true;
        this._rating = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool userId;
      public bool mode;
      public bool employeeInfo;
      public bool personEmploymentId;
      public bool requestId;
      public bool city;
      public bool dbStatus;
      public bool employeeIds;
      public bool rating;
    }

    public Employment() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              UserId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I16) {
              Mode = iprot.ReadI16();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Struct) {
              EmployeeInfo = new CompanyEmployeeInfo();
              EmployeeInfo.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I64) {
              PersonEmploymentId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.I64) {
              RequestId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.Struct) {
              City = new City();
              City.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == TType.Struct) {
              DbStatus = new DbStatus();
              DbStatus.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 8:
            if (field.Type == TType.String) {
              EmployeeIds = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 9:
            if (field.Type == TType.I32) {
              Rating = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Employment");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.userId) {
        field.Name = "userId";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(UserId);
        oprot.WriteFieldEnd();
      }
      if (__isset.mode) {
        field.Name = "mode";
        field.Type = TType.I16;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI16(Mode);
        oprot.WriteFieldEnd();
      }
      if (EmployeeInfo != null && __isset.employeeInfo) {
        field.Name = "employeeInfo";
        field.Type = TType.Struct;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        EmployeeInfo.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (__isset.personEmploymentId) {
        field.Name = "personEmploymentId";
        field.Type = TType.I64;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(PersonEmploymentId);
        oprot.WriteFieldEnd();
      }
      if (__isset.requestId) {
        field.Name = "requestId";
        field.Type = TType.I64;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(RequestId);
        oprot.WriteFieldEnd();
      }
      if (City != null && __isset.city) {
        field.Name = "city";
        field.Type = TType.Struct;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        City.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (DbStatus != null && __isset.dbStatus) {
        field.Name = "dbStatus";
        field.Type = TType.Struct;
        field.ID = 7;
        oprot.WriteFieldBegin(field);
        DbStatus.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (EmployeeIds != null && __isset.employeeIds) {
        field.Name = "employeeIds";
        field.Type = TType.String;
        field.ID = 8;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(EmployeeIds);
        oprot.WriteFieldEnd();
      }
      if (__isset.rating) {
        field.Name = "rating";
        field.Type = TType.I32;
        field.ID = 9;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Rating);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("Employment(");
      bool __first = true;
      if (__isset.userId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("UserId: ");
        __sb.Append(UserId);
      }
      if (__isset.mode) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Mode: ");
        __sb.Append(Mode);
      }
      if (EmployeeInfo != null && __isset.employeeInfo) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("EmployeeInfo: ");
        __sb.Append(EmployeeInfo== null ? "<null>" : EmployeeInfo.ToString());
      }
      if (__isset.personEmploymentId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("PersonEmploymentId: ");
        __sb.Append(PersonEmploymentId);
      }
      if (__isset.requestId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("RequestId: ");
        __sb.Append(RequestId);
      }
      if (City != null && __isset.city) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("City: ");
        __sb.Append(City== null ? "<null>" : City.ToString());
      }
      if (DbStatus != null && __isset.dbStatus) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("DbStatus: ");
        __sb.Append(DbStatus== null ? "<null>" : DbStatus.ToString());
      }
      if (EmployeeIds != null && __isset.employeeIds) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("EmployeeIds: ");
        __sb.Append(EmployeeIds);
      }
      if (__isset.rating) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Rating: ");
        __sb.Append(Rating);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
