/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace TekTak.iLoop.Kauwa
{
  public enum InstanceOperation
  {
    DELETE = 0,
    LEAVE = 1,
    LEAVE_DELETE = 2,
  }
}
