/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace TekTak.iLoop.Kauwa
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class WebOnlyFriendResponse : TBase
  {
    private List<WebOnlyFriend> _webOnlyFriends;
    private bool _hasNextPage;

    public List<WebOnlyFriend> WebOnlyFriends
    {
      get
      {
        return _webOnlyFriends;
      }
      set
      {
        __isset.webOnlyFriends = true;
        this._webOnlyFriends = value;
      }
    }

    public bool HasNextPage
    {
      get
      {
        return _hasNextPage;
      }
      set
      {
        __isset.hasNextPage = true;
        this._hasNextPage = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool webOnlyFriends;
      public bool hasNextPage;
    }

    public WebOnlyFriendResponse() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                WebOnlyFriends = new List<WebOnlyFriend>();
                TList _list108 = iprot.ReadListBegin();
                for( int _i109 = 0; _i109 < _list108.Count; ++_i109)
                {
                  WebOnlyFriend _elem110;
                  _elem110 = new WebOnlyFriend();
                  _elem110.Read(iprot);
                  WebOnlyFriends.Add(_elem110);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Bool) {
              HasNextPage = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("WebOnlyFriendResponse");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (WebOnlyFriends != null && __isset.webOnlyFriends) {
        field.Name = "webOnlyFriends";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, WebOnlyFriends.Count));
          foreach (WebOnlyFriend _iter111 in WebOnlyFriends)
          {
            _iter111.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (__isset.hasNextPage) {
        field.Name = "hasNextPage";
        field.Type = TType.Bool;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(HasNextPage);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("WebOnlyFriendResponse(");
      bool __first = true;
      if (WebOnlyFriends != null && __isset.webOnlyFriends) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("WebOnlyFriends: ");
        __sb.Append(WebOnlyFriends);
      }
      if (__isset.hasNextPage) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("HasNextPage: ");
        __sb.Append(HasNextPage);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
